name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
        
    - name: install wasm-tools
      run: dotnet workaload install wasm-tools

    - name: workaload repair
      run: dotnet workaload repair
      
    - name: publish
      run: dotnet publish NotBoosty.csproj -c Release --output release --nologo
      
    - name: Change base-tag in index.html from / to the necessary
      run: sed -i 's/<base href="\/" \/>/<base href="\/NotBoosty\/" \/>/g' release/wwwroot/index.html
      
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      name: gh-pages publish
      with:
        branch: gh-pages
        folder: release/wwwroot
